spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://ayeshu9696:eaAUjR7Gl0AmtiKv@cluster0.hulve.mongodb.net/mydb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=mydb
spring.security.filter.dispatcher-types=REQUEST,ASYNC
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayeshu9696@gmail.com
spring.mail.password=sweetheart6969
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
